### PR TITLE
Link a working build server.

### PR DESCRIPTION
**Pull request by DevJul1an**
In my opinion its good to have a EssentialsY buildserver linked hier.

If you have your own, you can close this pull request :)

### CODE REVIEW

**Comment by MiniDigger** [comment]
is that your server? can you guarantee that it will be reasonably stable and available?

**Comment by DevJul1an** [comment]
Thats the server of the network i'm admin on. Unless the Dedicated Server is down (which never happened before) it will be stable and online.

**Comment by MiniDigger** [comment]
ok, merging. thanks for saving me from the pain of trying to rescue my jenkins installation :D

**Comment by DevJul1an** [comment]
No Problem :)

**Pull request merged**
